- name: Install repositories
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - epel-release
    - centos-release-scl

- name: Set timezone to Europe/Moscow
  timezone:
    name: Europe/Moscow

- name: Install NTP
  yum:
    name: "{{ item }}"
    state: latest
  loop:
    - ntp
    - ntpdate
  notify:
    - Disable chronyd
    - Enable ntpd

- name: Install required packages
  yum:
    name: "{{ item }}"
    state: latest
  loop:
    - java
    - vim
    - net-tools
    - nmap
    - tcpdump
    - wget

- name: Disable SELinux
  selinux:
    state: disabled

- name: Disable THP
  copy:
    src: rc.local
    dest: /etc/rc.d/rc.local
    owner: root
    group: root
    mode: '0755'

- name: Configure swappiness
  sysctl:
    name: vm.swappiness
    value: '1'
    state: present
    reload: yes

- name: Put env script to profile.d
  copy:
    src: java.sh
    dest: /etc/profile.d/java.sh
    owner: root
    group: root
    mode: '0755'

#- name: Create directory for SSH keys
#  file:
#    path: "/root/.ssh"
#    state: directory
#    owner: root
#    group: root
#    mode: '0700'

#- name: Generate SSH keypair
#  openssh_keypair:
#    path: /root/.ssh/id_rsa
#    type: rsa
#    size: 2048
#    state: present
#  register: ssh_keypair

#- name: Add SSH Public key to fact
#  set_fact:
#    ssh_public_keys: "{{ ssh_public_keys + [ssh_keypair.public_key] }}"

#- name: Put public keys
#  authorized_key:
#    user: root
#    state: present
#    key: "{{ item }}"
#  loop: "{{ ssh_public_keys }}"