- name: Put yarn-site.xml
  template:
    src: yarn-site.j2.xml
    dest: "{{ hadoop_home }}/etc/hadoop/yarn-site.xml"
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart resourcemanager
    - Restart nodemanager

- name: Put mapred-site.xml
  template:
    src: mapred-site.j2.xml
    dest: "{{ hadoop_home }}/etc/hadoop/mapred-site.xml"
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart resourcemanager
    - Restart nodemanager

- name: Put capacity-scheduler.xml
  template:
    src: capacity-scheduler.j2.xml
    dest: "{{ hadoop_home }}/etc/hadoop/capacity-scheduler.xml"
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart resourcemanager
    - Restart nodemanager

- name: Configure ResourceManager
  include_tasks: configure_resourcemanager.yml
  when: inventory_hostname in rms

- name: Configure NodeManager
  include_tasks: configure_nodemanager.yml
  when: inventory_hostname in nms

- name: Temporary
  shell: /bin/true
  notify:
    - Restart resourcemanager
    - Restart nodemanager